-- ============================================================================
-- Seed-файл: Полный каталог тем Skola2030 (1–12 классы) и мультиязычные задачи
-- Запуск в Supabase: SQL Editor -> New query -> Вставить всё -> Run
-- ============================================================================

-- 0. Обновление ограничений до 12 классов и мультиязычность
alter table public.topics drop constraint if exists topics_grade_range;
alter table public.topics drop constraint if exists topics_grade_check;
alter table public.topics add constraint topics_grade_range check (grade is null or grade between 1 and 12);

alter table public.tasks drop constraint if exists tasks_grade_range;
alter table public.tasks drop constraint if exists tasks_grade_check;
alter table public.tasks add constraint tasks_grade_range check (grade is null or grade between 1 and 12);

alter table public.subjects add column if not exists title_lv text;

alter table public.topics add column if not exists title_lv text;
alter table public.topics add column if not exists description_lv text;

alter table public.tasks add column if not exists title_lv text;
alter table public.tasks add column if not exists condition_latex_lv text;
alter table public.tasks add column if not exists solution_latex_lv text;

-- 1. Базовые разделы Skola2030 (Lielās idejas / Mācību jomas)
insert into public.subjects (title, title_lv, slug, icon, position)
values
  ('Алгебра и числа', 'Algebra un skaitļi', 'algebra', 'x²', 1),
  ('Геометрия и измерения', 'Ģeometrija un mērījumi', 'geometry', '△', 2),
  ('Статистика и вероятность', 'Statistika un varbūtība', 'statistics', '📊', 3)
on conflict (slug) do update set
  title = excluded.title,
  title_lv = excluded.title_lv,
  icon = excluded.icon,
  position = excluded.position;

-- 2. Полный каталог тем стандарта Skola2030 (1–12 классы, 96 тем)
insert into public.topics (title, title_lv, slug, subject_id, grade, position, description, description_lv)
values
  ('1.1. Как рассказать и показать: сколько, где, какой', '1.1. Kā izstāsta un parāda: cik, kur, kāds?', 'skola2030-g1-1-rasskazat-i-pokazat-skolko', (select id from public.subjects where slug = 'geometry'), 1, 1, 'Фигуры (линия, многоугольник, круг). Характеристика, сравнение и группировка геометрических объектов; Последовательности предметов и чисел. Расположение и направления объектов на плоскости, в пространстве; Количество, счет. Число и его изображение, цифры', 'Figūras (līnija, daudzstūris, riņķis). Ģeometrisku objektu raksturošana, salīdzināšana, grupēšana; Priekšmetu un skaitļu virknes. Objektu novietojums un virzieni plaknē, telpā; Skaits, skaitīšana. Skaitlis un tā attēlošana, cipari'),
  ('1.2. Сколько всего, сколько осталось', '1.2. Cik kopā, cik palika?', 'skola2030-g1-2-skolko-vsego-skolko-ostalos', (select id from public.subjects where slug = 'algebra'), 1, 2, 'Сложение и вычитание в пределах 10; Состав числа. Его визуализация, запись; Таблица для записи данных', 'Saskaitīšana un atņemšana 10 apjomā; Skaitļa sastāvs. Tā vizualizēšana, pierakstīšana; Tabula datu pierakstīšanai'),
  ('1.3. Как измерять длины и получать симметричные фигуры', '1.3. Kā mēra garumus un kā iegūst simetrisku figūru?', 'skola2030-g1-3-izmeryat-dliny-i-poluchat', (select id from public.subjects where slug = 'geometry'), 1, 3, 'Определение, сравнение и вычисление длин; Симметричные фигуры', 'Garumu noteikšana, salīdzināšana un aprēķināšana; Simetriskas figūras'),
  ('1.4. Как записывают и сравнивают числа больше 10', '1.4. Kā pieraksta un salīdzina skaitļus, kuri ir lielāki nekā 10?', 'skola2030-g1-4-zapisyvayut-i-sravnivayut-chisla', (select id from public.subjects where slug = 'algebra'), 1, 4, 'Измерение длины (см) и сравнение; Десятичный состав, чтение и запись чисел 10-100; Сравнение чисел. Числовые последовательности', 'Garuma mērīšana (cm) un salīdzināšana; Skaitļu 10-100 decimālais sastāvs, lasīšana un pierakstīšana; Skaitļu salīdzināšana. Skaitļu virknes'),
  ('1.5. Как складывают и вычитают числа больше 10', '1.5. Kā saskaita un atņem skaitļus, kuri lielāki nekā 10?', 'skola2030-g1-5-skladyvayut-i-vychitayut-chisla', (select id from public.subjects where slug = 'algebra'), 1, 5, 'Вычитание в пределах 20; Прибавление однозначного числа к двузначному в пределах 20; Сложение однозначных чисел с переходом через 10', 'Atņemšana 20 apjomā; Viencipara skaitļa pieskaitīšana pie divciparu skaitļa 20 apjomā; Viencipara skaitļu saskaitīšana, ja rezultāts pārsniedz 10'),
  ('1.6. Что значит «на столько больше», «на столько меньше»', '1.6. Ko nozīmē “par tik vairāk”, “par tik mazāk”?', 'skola2030-g1-6-znachit-na-stolko-bolshe', (select id from public.subjects where slug = 'algebra'), 1, 6, 'Сравнение двух величин в пределах 20; Бытовые задачи, решаемые сложением и вычитанием в пределах 20', 'Divu lielumu salīdzināšana 20 apjomā; Sadzīves situāciju uzdevumi, kuru atrisināšanai izmanto saskaitīšanu un atņemšanu 20 apjomā'),
  ('1.7. Где мы встречаемся с большими числами', '1.7. Kur sastopamies ar lieliem skaitļiem?', 'skola2030-g1-7-my-vstrechaemsya-s-bolshimi', (select id from public.subjects where slug = 'algebra'), 1, 7, 'Измерение длины (см, дм, м); Измерение/отсчет времени; Деньги (евро, центы); Сложение и вычитание в пределах 100. Бытовые ситуации', 'Garuma mērīšana (cm, dm, m); Laika mērīšana/skaitīšana; Nauda (eiro, centi); Saskaitīšana un atņemšana 100 apjomā. Sadzīves situācijas'),
  ('1.8. Как описывают и создают фигуры', '1.8. Kā apraksta un veido figūras?', 'skola2030-g1-8-apraksta-un-veido-figuras', (select id from public.subjects where slug = 'geometry'), 1, 8, 'Геометрические фигуры на плоскости и в пространстве. Создание фигур из деталей, рисование и характеристика', 'Ģeometriskas figūras plaknē un telpā. Figūru veidošana no detaļām, zīmēšana un raksturošana'),
  ('2.1. Как группируют объекты', '2.1. Kā grupē objektus?', 'skola2030-g2-1-grupe-objektus', (select id from public.subjects where slug = 'statistics'), 2, 1, 'Группировка объектов по признакам, упорядочивание данных в таблицах и диаграммах', 'Objektu grupēšana pēc pazīmēm, datu kārtošana tabulās un diagrammās'),
  ('2.2. Как определяют различные длины', '2.2. Kā nosaka dažādus garumus?', 'skola2030-g2-2-nosaka-dazadus-garumus', (select id from public.subjects where slug = 'geometry'), 2, 2, 'Измерение и сравнение длины (миллиметры, сантиметры, дециметры, метры). Построение отрезков', 'Garuma mērīšana un salīdzināšana (milimetri, centimetri, decimetri, metri). Nogriežņu zīmēšana'),
  ('2.3. Как складывают и вычитают двузначные числа', '2.3. Kā saskaita un atņem divciparu skaitļus?', 'skola2030-g2-1-skladyvayut-i-vychitayut-dvuznachnye', (select id from public.subjects where slug = 'algebra'), 2, 3, 'Сложение и вычитание в пределах 100. Бытовые ситуации; Сложение и вычитание в пределах 20', 'Saskaitīšana un atņemšana 100 apjomā. Sadzīves situācijas; Saskaitīšana un atņemšana 20 apjomā'),
  ('2.4. Как расчет времени помогает планировать', '2.4. Kā laika rēķini palīdz plānot?', 'skola2030-g2-4-laika-rekini-palidz-planot', (select id from public.subjects where slug = 'algebra'), 2, 4, 'Единицы измерения времени (часы, минуты, дни, месяцы), чтение часов и планирование времени', 'Laika mērvienības (stundas, minūtes, dienas, mēneši), pulksteņa lasīšana un laika plānošana'),
  ('2.5. Как возникает выражение', '2.5. Kā rodas izteiksme?', 'skola2030-g2-5-rodas-izteiksme', (select id from public.subjects where slug = 'algebra'), 2, 5, 'Числовые выражения со скобками и без. Порядок действий и моделирование текстовых ситуаций', 'Skaitliskas izteiksmes ar iekavām un bez tām. Darbību secība un tekstveida situāciju modelēšana'),
  ('2.6. Как создают и характеризуют фигуры', '2.6. Kā veido un raksturo figūras?', 'skola2030-g2-6-veido-un-raksturo-figuras', (select id from public.subjects where slug = 'geometry'), 2, 6, 'Виды многоугольников (треугольники, четырёхугольники), их стороны и вершины. Сравнение фигур', 'Daudzstūru veidi (trijstūri, četrstūri), to malas un virsotnes. Figūru salīdzināšana'),
  ('2.7. Что значит умножать и делить на 2', '2.7. Ko nozīmē reizināt un dalīt ar 2?', 'skola2030-g2-7-reizinat-un-dalit-ar-2', (select id from public.subjects where slug = 'algebra'), 2, 7, 'Смысл умножения и деления на 2, половина и удвоенное количество, решение задач', 'Reizināšanas un dalīšanas ar 2 jēga, puse un divkāršs apjoms, uzdevumu risināšana'),
  ('2.8. Как умножают и делят на 3, 4 и 5', '2.8. Kā reizina un dala ar 3, 4 un 5?', 'skola2030-g2-2-umnozhayut-i-delyat-na', (select id from public.subjects where slug = 'algebra'), 2, 8, 'Как умножают и делят на 3 и 4?; Как умножают и делят на 5? Умножение и деление в пределах 50', 'Kā reizina un dala ar 3 un 4?; Kā reizina un dala ar 5? Reizināšana un dalīšana 50 apjomā'),
  ('3.1. Как умножают и делят на 6, 7, 8, 9 и 10', '3.1. Kā reizina un dala ar 6, 7, 8, 9 un 10?', 'skola2030-g3-1-umnozhayut-i-delyat-na', (select id from public.subjects where slug = 'algebra'), 3, 1, 'Умножение и деление двузначных чисел; Таблица умножения. Умножение и деление в различных ситуациях', 'Divciparu skaitļu reizināšana un dalīšana; Reizināšanas tabula. Reizināšana un dalīšana dažādās situācijās'),
  ('3.2. Как используют все действия', '3.2. Kā izmanto visas darbības?', 'skola2030-g3-2-ispolzuyut-vse-deystviya', (select id from public.subjects where slug = 'algebra'), 3, 2, 'Насколько хорошо я умею выполнять действия с числами в пределах 100?; Числовые выражения; Формулы вычисления периметра прямоугольника', 'Cik labi protu veikt darbības ar skaitļiem 100 apjomā?; Skaitliskas izteiksmes; Taisnstūra perimetra aprēķināšanas formulas'),
  ('3.3. Как составляют план местности', '3.3. Kā veido vietas plānu?', 'skola2030-g3-3-sostavlyayut-plan-mestnosti', (select id from public.subjects where slug = 'geometry'), 3, 3, 'Умножение и деление многозначных чисел на 10, 100 и полные десятки; План помещения; Трехзначные и четырехзначные числа', 'Daudzciparu skaitļu reizināšana un dalīšana ar 10, 100 un pilniem desmitiem; Telpas plāns; Trīsciparu un četrciparu skaitļi'),
  ('3.4. Что значит часть от целого', '3.4. Ko nozīmē daļa no veselā?', 'skola2030-g3-4-znachit-chast-ot-tselogo', (select id from public.subjects where slug = 'algebra'), 3, 4, 'Деление на равные части, целое и часть; Часть от количества; Запись дроби. Дроби можно складывать. Дроби на числовой прямой.; Сравнение дробей', 'Dalīšana vienādās daļās, veselais un daļa; Daļa no skaita; Daļskaitļa pieraksts. Daļskaitļi uz skaitļu taisnes; Daļu salīdzināšana'),
  ('3.5. Какие величины характеризуют фигуру', '3.5. Kādi lielumi raksturo figūru?', 'skola2030-g3-5-kadi-lielumi-raksturo-figuru', (select id from public.subjects where slug = 'geometry'), 3, 5, 'Периметр прямоугольника и квадрата, измерение площади квадратными единицами', 'Taisnstūra un kvadrāta perimetrs, laukuma mērīšana ar kvadrātvienībām'),
  ('3.6. Как складывают и вычитают трёхзначные числа', '3.6. Kā saskaita un atņem trīsciparu skaitļus?', 'skola2030-g3-6-saskaita-un-atnem-trisciparu', (select id from public.subjects where slug = 'algebra'), 3, 6, 'Сложение и вычитание трёхзначных чисел столбиком и устно, бытовые расчёты', 'Trīsciparu skaitļu saskaitīšana un atņemšana stabiņā un galvā, sadzīves aprēķini'),
  ('3.7. Как создают пространственные модели', '3.7. Kā veido telpiskus modeļus?', 'skola2030-g3-5-sozdayut-prostranstvennye-modeli', (select id from public.subjects where slug = 'geometry'), 3, 7, 'Пространственные фигуры; Развертки пространственных фигур, вид пространственной фигуры с разных сторон', 'Telpiskas figūras; Telpisku figūru izklājumi, kā telpiska figūra izskatās no dažādām pusēm'),
  ('4.1. Как складывают и вычитают многозначные числа', '4.1. Kā saskaita un atņem daudzciparu skaitļus?', 'skola2030-g4-1-skladyvayut-i-vychitayut-mnogoznachnye', (select id from public.subjects where slug = 'algebra'), 4, 1, 'Первая тысяча (повторение); Четырехзначные числа. Сложение и вычитание четырехзначных чисел', 'Pirmais tūkstotis (atkārtojums); Četrciparu skaitļi. Četrciparu skaitļu saskaitīšana un atņemšana'),
  ('4.2. Как многозначные числа умножают и делят на однозначное число', '4.2. Kā daudzciparu skaitļus reizina un dala ar viencipara skaitli?', 'skola2030-g4-2-mnogoznachnye-chisla-umnozhayut-i', (select id from public.subjects where slug = 'algebra'), 4, 2, 'Деление двузначного числа на однозначное; Умножение двузначного числа на однозначное; Деление трехзначного числа на однозначное; Умножение трехзначного числа на однозначное', 'Divciparu skaitļa dalīšana ar viencipara skaitli; Divciparu skaitļa reizināšana ar viencipara skaitli; Trīsciparu skaitļa dalīšana ar viencipara skaitli; Trīsciparu skaitļa reizināšana ar viencipara skaitli'),
  ('4.3. Как измеряют углы', '4.3. Kā mēra leņķi?', 'skola2030-g4-3-ka-mera-lenki', (select id from public.subjects where slug = 'geometry'), 4, 3, 'Понятие угла, виды углов (острый, прямой, тупой, развёрнутый), измерение углов транспортиром и построение', 'Leņķa jēdziens, leņķu veidi (šaurs, taisns, plats, izstiepts), leņķu mērīšana ar transportieri un zīmēšana'),
  ('4.4. Как многозначные числа умножают и делят на двузначное число', '4.4. Kā daudzciparu skaitļus reizina un dala ar divciparu skaitli?', 'skola2030-g4-3-mnogoznachnye-chisla-umnozhayut-i', (select id from public.subjects where slug = 'algebra'), 4, 4, 'Деление многозначного числа на двузначное; Умножение многозначного числа на двузначное', 'Daudzciparu skaitļa dalīšana ar divciparu skaitli; Daudzciparu skaitļa reizināšana ar divciparu skaitli'),
  ('4.5. Как сравнивают, складывают и вычитают дроби', '4.5. Kā salīdzina, saskaita un atņem daļskaitļus?', 'skola2030-g4-4-sravnivayut-skladyvayut-i-vychitayut', (select id from public.subjects where slug = 'algebra'), 4, 5, 'Дробь как произведение числителя и основной дроби; Дроби, их расположение на числовой прямой; Сложение и вычитание дробей с одинаковыми знаменателями; Сравнение дробей', 'Daļa kā skaitītāja un pamatdaļas reizinājums; Daļas, to novietojums uz skaitļu taisnes; Daļu ar vienādiem saucējiem saskaitīšana un atņemšana; Daļu salīdzināšana'),
  ('4.6. Что значит часть от целого', '4.6. Ko nozīmē daļa no veselā?', 'skola2030-g4-5-znachit-chast-ot-tselogo', (select id from public.subjects where slug = 'algebra'), 4, 6, 'Целое — это числовое значение величины; Целое состоит из нескольких элементов; Нахождение части от величины и числа', 'Veselais ir lieluma skaitliskā vērtība; Veselo veido vairāki elementi; Daļa no lieluma un daļa no skaita'),
  ('4.7. Как определяют площадь различных фигур', '4.7. Kā nosaka dažādu figūru laukumu?', 'skola2030-g4-7-nosaka-dazadu-figuru-laukumu', (select id from public.subjects where slug = 'geometry'), 4, 7, 'Вычисление площади прямоугольника и составных фигур, единицы площади (см², дм², м²)', 'Taisnstūra un kombinētu taisnstūrveida figūru laukuma aprēķināšana, laukuma mērvienības (cm², dm², m²)'),
  ('4.8. Что общего в математическом описании покупок и движения', '4.8. Kas kopīgs iepirkšanās un kustības matemātiskajā aprakstā?', 'skola2030-g4-6-obshchego-v-matematicheskom-opisanii', (select id from public.subjects where slug = 'algebra'), 4, 8, 'Время, путь, скорость; Количество, оплата, цена. Уравнения и зависимости между величинами', 'Laiks, ceļš, ātrums; Skaits, samaksa, cena. Vienādojumi un sakarības starp lielumiem'),
  ('5.1. Как по-разному записывают натуральные числа', '5.1. Kā dažādi pieraksta naturālos skaitļus?', 'skola2030-g5-1-po-raznomu-zapisyvayut-naturalnye', (select id from public.subjects where slug = 'algebra'), 5, 1, 'Другие системы записи натуральных чисел; Запись натуральных чисел в десятичной системе; Округление натуральных чисел; Закономерности между компонентами действий в суммах и разностях', 'Citas naturālo skaitļu pieraksta sistēmas; Naturālo skaitļu pieraksts decimālajā sistēmā; Naturālu skaitļu noapaļošana; Sakarības starp darbību locekļiem summās un starpībās'),
  ('5.2. Как используют разложение числа на множители', '5.2. Kā lieto skaitļa sadalīšanu reizinātājos?', 'skola2030-g5-2-ispolzuyut-razlozhenie-chisla-na', (select id from public.subjects where slug = 'algebra'), 5, 2, 'Возведение в степень; Приемы умножения, деления и свойства действий; Разложение на множители', 'Kāpināšana; Reizināšanas, dalīšanas paņēmieni un darbību īpašības; Sadalīšana reizinātājos'),
  ('5.3. Как объясняют и применяют основное свойство дроби', '5.3. Kā skaidro un lieto daļas pamatīpašību?', 'skola2030-g5-3-obyasnyayut-i-primenyayut-osnovnoe', (select id from public.subjects where slug = 'algebra'), 5, 3, 'Основное свойство дроби; Сложение и вычитание дробей с разными знаменателями; Сравнение дробей; Деление основной дроби на целое число', 'Daļas pamatīpašība; Daļu ar dažādiem saucējiem saskaitīšana un atņemšana; Daļu salīdzināšana; Pamatdaļas dalīšana ar veselu skaitli'),
  ('5.4. Как одно число выражают как часть другого числа', '5.4. Kā vienu skaitli izsaka kā otra skaitļa daļu?', 'skola2030-g5-4-odno-chislo-vyrazhayut-chast', (select id from public.subjects where slug = 'algebra'), 5, 4, 'Дробь как запись действия деления; Дробь и числовое значение целого', 'Daļa kā dalīšanas darbības pieraksts; Daļas un veselā skaitliskā vērtība'),
  ('5.5. Как складывают и вычитают смешанные числа', '5.5. Kā saskaita un atņem jauktus skaitļus?', 'skola2030-g5-5-skladyvayut-i-vychitayut-smeshannye', (select id from public.subjects where slug = 'algebra'), 5, 5, 'Смешанные числа; Сложение и вычитание смешанных чисел; Сложение и вычитание смешанных чисел, если знаменатели разные', 'Jaukti skaitļi; Jauktu skaitļu saskaitīšana un atņemšana; Jauktu skaitļu saskaitīšana un atņemšana, ja saucēji ir dažādi'),
  ('5.6. Как определяют неизвестные величины фигур', '5.6. Kā nosaka figūru nezināmos lielumus?', 'skola2030-g5-6-opredelyayut-neizvestnye-velichiny-figur', (select id from public.subjects where slug = 'geometry'), 5, 6, 'Свойства и величины многоугольников; Угол. Угол как сумма или разность других углов; Окружность и её длина', 'Daudzstūru īpašības un lielumi; Leņķis. Leņķis kā citu leņķu summa vai starpība; Riņķa līnija un tās garums'),
  ('5.7. Как используют десятичные дроби и проценты', '5.7. Kā lieto decimāldaļas un procentus?', 'skola2030-g5-7-ispolzuyut-desyatichnye-drobi-i', (select id from public.subjects where slug = 'statistics'), 5, 7, 'Десятичные дроби, их изображение на числовой прямой и сравнение; Сложение и вычитание десятичных дробей; Проценты; Задачи на проценты; Круговая диаграмма', 'Decimāldaļas, to attēlojums uz skaitļu taisnes un salīdzināšana; Decimāldaļu saskaitīšana un atņemšana; Procenti; Procentu uzdevumi; Sektoru diagramma'),
  ('5.8. Как визуально отображают зависимость между величинами', '5.8. Kā vizuāli attēlo sakarību starp lielumiem?', 'skola2030-g5-8-vizuali-attelo-sakaribu', (select id from public.subjects where slug = 'statistics'), 5, 8, 'Графическое представление данных, столбчатые и линейные диаграммы, считывание зависимостей между переменными', 'Datu grafiskā attēlošana, stabiņu un līniju diagrammas, divu mainīgo sakarību nolasīšana'),
  ('6.1. Как совокупность делят в определенном отношении', '6.1. Kā kopumu sadala noteiktā attiecībā?', 'skola2030-g6-1-sovokupnost-delyat-v-opredelennom', (select id from public.subjects where slug = 'algebra'), 6, 1, 'Масштаб; Пропорциональные величины; Отношения чисел. Деление совокупности в определенном отношении', 'Mērogs; Proporcionāli lielumi; Skaitļu attiecības. Kopuma sadalīšana noteiktā attiecībā'),
  ('6.2. Как умножают и делят обыкновенные дроби', '6.2. Kā reizina un dala parastās daļas?', 'skola2030-g6-2-umnozhayut-i-delyat-obyknovennye', (select id from public.subjects where slug = 'algebra'), 6, 2, 'Умножение и деление дробей и смешанных чисел на целое число; Умножение и деление обыкновенных дробей между собой', 'Daļu un jauktu skaitļu reizināšana un dalīšana ar veselu skaitli; Parasto daļu reizināšana un dalīšana savā starpā'),
  ('6.3. Как понимание запятой помогает при умножении и делении десятичных дробей', '6.3. Kā izpratne par komata lietojumu palīdz, ja reizina un dala decimāldaļas?', 'skola2030-g6-3-komata-lietojums-decimaldalas', (select id from public.subjects where slug = 'algebra'), 6, 3, 'Умножение и деление десятичных дробей на 10, 100, 1000 и между собой. Правила переноса запятой и округление', 'Decimāldaļu reizināšana un dalīšana ar 10, 100, 1000 un savā starpā. Komata pārvietošanas likumi un noapaļošana'),
  ('6.4. Как изображают и характеризуют пространственные тела', '6.4. Kā attēlo un raksturo telpiskus ķermeņus?', 'skola2030-g6-3-izobrazhayut-i-kharakterizuyut-prostranstvennye', (select id from public.subjects where slug = 'geometry'), 6, 4, 'Объем; Площадь поверхности; Прямоугольный параллелепипед и куб, их развертки', 'Tilpums; Virsmas laukums; Taisnstūra paralēlskaldnis un kubs, to izklājumi'),
  ('6.5. Как в жизненных ситуациях используют проценты', '6.5. Kā sadzīves situācijās izmanto procentus?', 'skola2030-g6-5-sadzives-situacijas-procentus', (select id from public.subjects where slug = 'statistics'), 6, 5, 'Нахождение процента от числа, нахождение числа по его проценту, изменение цен, скидки и налоги', 'Procentu aprēķināšana no skaitļa, skaitļa atrašana pēc tā procentiem, cenu izmaiņas, atlaides un nodokļi'),
  ('6.6. Зачем нужны числа, которые меньше нуля', '6.6. Kāpēc nepieciešami skaitļi, kuri ir mazāki nekā nulle?', 'skola2030-g6-4-nuzhny-chisla-kotorye-menshe', (select id from public.subjects where slug = 'algebra'), 6, 6, 'Противоположные числа. Положительные и отрицательные числа, их расположение на числовой прямой, модуль и сравнение', 'Pretēji skaitļi. Pozitīvi un negatīvi skaitļi, to novietojums uz skaitļu taisnes, moduļa jēdziens un salīdzināšana'),
  ('6.7. Что значит прибавить к числу отрицательное число или вычесть отрицательное число', '6.7. Ko nozīmē skaitlim pieskaitīt negatīvu skaitli, no skaitļa atņemt negatīvu skaitli?', 'skola2030-g6-5-znachit-pribavit-k-chislu', (select id from public.subjects where slug = 'algebra'), 6, 7, 'Сложение и вычитание положительных и отрицательных дробей; Сложение и вычитание целых чисел', 'Pozitīvu un negatīvu daļskaitļu saskaitīšana un atņemšana; Veselu skaitļu saskaitīšana un atņemšana'),
  ('6.8. Как планируют порядок действий со всеми видами чисел', '6.8. Kā plāno darbību izpildi ar visu veidu skaitļiem?', 'skola2030-g6-8-plano-darbibu-izpildi', (select id from public.subjects where slug = 'algebra'), 6, 8, 'Все четыре действия с рациональными числами (целые числа, обыкновенные дроби, десятичные дроби). Вычисление сложных выражений', 'Visas četras darbības ar racionāliem skaitļiem (veseli skaitļi, parastās daļas, decimāldaļas). Izteiksmju aprēķināšana'),
  ('7.1. Как определяют все элементы множества, вычисляют вероятность события', '7.1. Kā nosaka kopas visus elementus, aprēķina notikuma varbūtību?', 'skola2030-g7-1-opredelyayut-vse-elementy-mnozhestva', (select id from public.subjects where slug = 'statistics'), 7, 1, 'Создание выборок, их характеристика, определение количества выборок; Множества, диаграмма Эйлера-Венна. Полный перебор; Вероятность и её применения', 'Izlašu veidošana, raksturošana, izlašu skaita noteikšana; Kopas, Eilera-Venna diagramma. Pilnā pārlase; Varbūtība un tās lietojumi'),
  ('7.2. Как определяют геометрические фигуры', '7.2. Kā definē ģeometriskas figūras?', 'skola2030-g7-2-opredelyayut-geometricheskie-figury', (select id from public.subjects where slug = 'geometry'), 7, 2, 'Взаимное расположение двух прямых на плоскости. Угол; Равные фигуры. Длина отрезка и её вычисление; Определение и изображение геометрических фигур', 'Divu taišņu novietojums plaknē. Leņķis; Vienādas figūras. Nogriežņa garums un tā aprēķināšana; Ģeometrisko figūru definēšana un attēlošana'),
  ('7.3. Как характеризуют зависимость между переменными величинами', '7.3. Kā raksturo sakarību starp mainīgiem lielumiem?', 'skola2030-g7-3-kharakterizuyut-zavisimost-mezhdu-peremennymi', (select id from public.subjects where slug = 'algebra'), 7, 3, 'Зависимость между обратно пропорциональными величинами и другие виды зависимостей; Зависимость между прямо пропорциональными величинами', 'Sakarība starp apgriezti proporcionāliem lielumiem un cita veida sakarības; Sakarība starp tieši proporcionāliem lielumiem'),
  ('7.4. Как записывают и исследуют функции, график которых — прямая', '7.4. Kā pieraksta un pēta funkcijas, kuru grafiks ir taisne?', 'skola2030-g7-4-zapisyvayut-i-issleduyut-funktsii', (select id from public.subjects where slug = 'algebra'), 7, 4, 'Функция, связанные с ней понятия. Линейная функция; Свойства линейной функции', 'Funkcija, ar to saistītie jēdzieni. Lineāra funkcija; Lineāras funkcijas īpašības'),
  ('7.5. Как характеризуют треугольник, используя его элементы', '7.5. Kā raksturo trijstūri, izmantojot tā elementus?', 'skola2030-g7-5-kharakterizuyut-treugolnik-ispolzuya-ego', (select id from public.subjects where slug = 'geometry'), 7, 5, 'Серединный перпендикуляр отрезка и характерные отрезки в треугольнике; Треугольники с равными сторонами; Расположение трех точек на плоскости. Треугольник; Равные треугольники, признаки равенства и их применение', 'Nogriežņa vidusperpendikuls un raksturīgie nogriežņi trijstūrī; Trijstūri ar vienādām malām; Triju punktu novietojums plaknē.Trijstūris; Vienādi trijstūri, vienādības pazīmes un to lietošana'),
  ('7.6. Каковы зависимости между величинами в треугольнике', '7.6. Kādas ir sakarības starp lielumiem trijstūrī?', 'skola2030-g7-6-zavisimosti-mezhdu-velichinami-v', (select id from public.subjects where slug = 'geometry'), 7, 6, 'Зависимости между сторонами и углами треугольника. Свойства и признаки треугольника; Сумма углов треугольника; Расположение трех прямых на плоскости', 'Sakarības starp trijstūra malām un leņķiem. Trijstūra īpašības un pazīmes; Trijstūra leņķu summa; Trīs taišņu novietojums plaknē'),
  ('7.7. Что значит преобразовать выражение с переменной величиной', '7.7. Ko nozīmē pārveidot izteiksmi ar mainīgo lielumu?', 'skola2030-g7-7-znachit-preobrazovat-vyrazhenie-s', (select id from public.subjects where slug = 'algebra'), 7, 7, 'Алгебраические выражения и их значение; Преобразования алгебраических выражений; Тождественно равные выражения; Числовые и алгебраические выражения', 'Algebriskas izteiksmes un to vērtība; Algebrisku izteiksmju pārveidojumi; Identiski vienādas izteiksmes; Skaitliskas un algebriskas izteiksmes'),
  ('7.8. Каковы приемы определения неизвестного, линейное уравнение', '7.8. Kādi ir paņēmieni nezināmā noteikšanai?', 'skola2030-g7-8-priemy-opredeleniya-neizvestnogo-lineynoe', (select id from public.subjects where slug = 'algebra'), 7, 8, 'Использование линейного уравнения при решении текстовых задач; Линейное уравнение и его решение; Пропорция. Выражение величины из пропорции; Эквивалентные преобразования уравнения', 'Lineāra vienādojuma lietojums teksta uzdevumu atrisināšanā; Lineārs vienādojums un tā atrisināšana; Proporcija. Lieluma izteikšana no proporcijas; Vienādojuma ekvivalenti pārveidojumi'),
  ('7.9. Как сравнивают выражения, где есть переменная, неравенства', '7.9. Kā salīdzina izteiksmes, kurās ir mainīgais lielums?', 'skola2030-g7-9-sravnivayut-vyrazheniya-est-peremennaya', (select id from public.subjects where slug = 'algebra'), 7, 9, 'Сравнение выражений. Неравенство и его решение; Решение линейных неравенств; Применение неравенств', 'Izteiksmju salīdzināšana. Nevienādība un tās atrisinājums; Lineāru nevienādību atrisināšana; Nevienādību lietošana'),
  ('8.1. Как математически описывают и анализируют данные, статистика', '8.1. Kā matemātiski raksturo un analizē datus?', 'skola2030-g8-1-matematicheski-opisyvayut-i-analiziruyut', (select id from public.subjects where slug = 'statistics'), 8, 1, 'Сбор, обобщение и отображение данных; Упорядочивание данных и статистические показатели', 'Datu ieguve, apkopošana un attēlošana; Datu sakārtošana un statistiskie rādītāji'),
  ('8.2. Как объясняют и применяют степень с целым показателем', '8.2. Kā skaidro un lieto pakāpi ar veselu kāpinātāju?', 'skola2030-g8-2-obyasnyayut-i-primenyayut-stepen', (select id from public.subjects where slug = 'algebra'), 8, 2, 'Степень с натуральным показателем и свойства; Степень с целым показателем', 'Pakāpe ar naturālu kāpinātāju un īpašības; Pakāpe ar veselu kāpinātāju'),
  ('8.3. Как поступают, если число нельзя записать в виде дроби, квадратный корень', '8.3. Kā rīkojas, ja skaitli nevar pierakstīt kā daļu?', 'skola2030-g8-3-postupayut-esli-chislo-nelzya', (select id from public.subjects where slug = 'algebra'), 8, 3, 'Арифметический квадратный корень; Свойства арифметического квадратного корня; Приближения точного значения чисел. Рациональные и иррациональные числа', 'Aritmētiskā kvadrātsakne; Aritmētiskās kvadrātsaknes īpašības; Skaitļu precīzās vērtības tuvinājumi. Racionāli un iracionāli skaitļi'),
  ('8.4. Как вычисляют площадь для любого треугольника, круга, призмы, цилиндра', '8.4. Kā aprēķina laukumu jebkuram trijstūrim, riņķim?', 'skola2030-g8-4-vychislyayut-ploshchad-dlya-lyubogo', (select id from public.subjects where slug = 'geometry'), 8, 4, 'Цилиндр, площадь его поверхности и объем; Площадь. Площадь треугольника; Площадь круга. Площадь комбинированных фигур; Прямая призма, площадь её поверхности и объем', 'Cilindrs, tā virsmas laukums un tilpums; Laukums. Trijstūra laukums; Riņķa laukums. Kombinētu figūru laukums; Taisna prizma, tās virsmas laukums un tilpums'),
  ('8.5. Что общего у четырехугольников, противоположные стороны которых попарно параллельны', '8.5. Kas kopīgs četrstūriem, kuru pretējās malas ir pa pāriem paralēlas?', 'skola2030-g8-5-obshchego-u-chetyrekhugolnikov-protivopolozhnye', (select id from public.subjects where slug = 'geometry'), 8, 5, 'Площадь параллелограмма; Параллелограмм; Ромб и прямоугольник; Признаки параллельности прямых; Четырехугольники', 'Paralelograma laukums; Paralelograms; Rombs un taisnstūris; Taišņu paralelitātes pazīmes; Četrstūri'),
  ('8.6. Как объясняют и выполняют действия с выражениями', '8.6. Kā skaidro un izpilda darbības ar izteiksmēm?', 'skola2030-g8-6-obyasnyayut-i-vypolnyayut-deystviya', (select id from public.subjects where slug = 'algebra'), 8, 6, 'Произведение одночлена и многочлена; Одночлены, их сложение и вычитание; Умножение, деление, возведение в степень одночленов; Произведение многочлена на многочлен; Многочлены, их сложение и вычитание', 'Monoma un polinoma reizinājums; Monomi, to saskaitīšana un atņemšana; Monomu reizināšana, dalīšana, kāpināšana; Polinoma reizinājums ar polinomu; Polinomi, to saskaitīšana un atņemšana'),
  ('8.7. Как различные функции используют для математического моделирования', '8.7. Kā dažādas funkcijas izmanto matemātiskai modelēšanai?', 'skola2030-g8-7-razlichnye-funktsii-ispolzuyut-dlya', (select id from public.subjects where slug = 'algebra'), 8, 7, 'Функция y=k/x; Квадратичная функция, свойства; График квадратичной функции', 'Funkcija y=k/x; Kvadrātfunkcija, īpašības; Kvadrātfunkcijas grafiks'),
  ('8.8. Как определяют неизвестную сторону прямоугольного треугольника, теорема Пифагора', '8.8. Kā nosaka taisnleņķa trijstūra nezināmās malas garumu?', 'skola2030-g8-8-opredelyayut-neizvestnuyu-storonu-pryamougolnogo', (select id from public.subjects where slug = 'geometry'), 8, 8, 'Теорема Пифагора и её применение; Прямоугольный треугольник, равенство прямоугольных треугольников', 'Pitagora teorēma un tās lietojums; Taisleņķa trijstūris, taisleņķa trijstūru vienādība'),
  ('9.1. Как определяют и характеризуют подобные треугольники', '9.1. Kā definē un raksturo līdzīgus trijstūrus?', 'skola2030-g9-1-opredelyayut-i-kharakterizuyut-podobnye', (select id from public.subjects where slug = 'geometry'), 9, 1, 'Подобные треугольники, признаки подобия треугольников; Теорема Фалеса. Пропорциональные отрезки; Средняя линия треугольника; Применение подобия треугольников', 'Līdzīgi trijstūri, trijstūru līdzības pazīmes; Talesa teorēma. Proporcionāli nogriežņi; Trijstūra viduslīnija; Trijstūru līdzības lietojums'),
  ('9.2. Что общего у четырехугольников, у которых ровно две стороны параллельны, трапеция', '9.2. Kas kopīgs četrstūriem, kuriem tieši divas malas ir paralēlas?', 'skola2030-g9-2-obshchego-u-chetyrekhugolnikov-u', (select id from public.subjects where slug = 'geometry'), 9, 2, 'Прямая четырехугольная призма, пространственные тела; Трапеция, прямоугольная трапеция; Средняя линия трапеции. Площадь трапеции; Равнобедренная трапеция', 'Taisna četrstūra prizma, telpiski ķermeņi; Trapece, taisnleņķa trapece; Trapeces viduslīnija. Trapeces laukums; Vienādsānu trapece'),
  ('9.3. Как в вычислениях используют отношение двух сторон прямоугольного треугольника', '9.3. Kā aprēķinos izmanto taisnleņķa trijstūra divu malu attiecību?', 'skola2030-g9-3-v-vychisleniyakh-ispolzuyut-otnoshenie', (select id from public.subjects where slug = 'geometry'), 9, 3, 'Зависимости в прямоугольном треугольнике в математических и реальных контекстах; Определение sin, cos, tg, вычисление неизвестных величин в прямоугольном треугольнике', 'Sakarības taisnleņķa trijstūrī matemātiskos un reālos kontekstos; Sin, cos, tg definēšana, nezināmo lielumu aprēķināšana taisnleņķa trijstūrī'),
  ('9.4. Как используют разложение выражений на множители', '9.4. Kā izmanto izteiksmju sadalīšanu reizinājos?', 'skola2030-g9-4-ispolzuyut-razlozhenie-vyrazheniy-na', (select id from public.subjects where slug = 'algebra'), 9, 4, 'Квадрат двучлена; Разность квадратов; Разложение многочлена на множители вынесением общего множителя за скобки; Применение всех действий с одночленами, многочленами', 'Binoma kvadrāts; Kvadrātu starpība; Polinoma sadalīšana reizinātājos, iznesot kopīgo reizinātāju pirms iekavām; Visu darbību ar monomiem, polinomiem lietojums'),
  ('9.5. Как объясняют и используют формулы при работе с квадратным уравнением, квадратичной функцией', '9.5. Kā skaidro un izmanto formulas darbā ar kvadrātvienādojumu, kvadrātfunkciju?', 'skola2030-g9-5-obyasnyayut-i-ispolzuyut-formuly', (select id from public.subjects where slug = 'algebra'), 9, 5, 'Квадратичные функции; Квадратные неравенства; Формула корней квадратного уравнения; Квадратные уравнения x²=t, ax²=t и (x+k)²=t; Квадратное уравнение; Произведение, равное 0, уравнения ax²+bx=0; Теорема Виета', 'Kvadrātfunkcijas; Kvadrātnevienādības; Kvadrātvienādojuma sakņu formula; Kvadrātvienādojumi x²=t, ax²=t un (x+k)²=t; Kvadrātvienādojums; Reizinājums vienāds ar 0, vienādojumi ax²+bx=0; Vjeta teorēma'),
  ('9.6. Как описывают ситуации с двумя неизвестными величинами', '9.6. Kā apraksta situācijas ar diviem nezināmiem lielumiem?', 'skola2030-g9-6-opisyvayut-situatsii-s-dvumya', (select id from public.subjects where slug = 'algebra'), 9, 6, 'Уравнение с двумя неизвестными, его графическое изображение; Решение систем уравнений графическим способом; Аналитические способы решения систем уравнений; Способ подстановки; Способ сложения', 'Vienādojums ar diviem nezināmajiem, tā grafiskais attēlojums; Vienādojumu sistēmas atrisināšana grafiski; Vienādojumu sistēmas atrisināšanas analītiskie paņēmieni; Ievietošanas paņēmiens; Saskaitīšanas paņēmiens'),
  ('9.7. Как числовую последовательность записывают формулой', '9.7. Kā skaitļu virkni pieraksta ar formulu?', 'skola2030-g9-7-chislovuyu-posledovatelnost-zapisyvayut-formuloy', (select id from public.subjects where slug = 'algebra'), 9, 7, 'Арифметическая прогрессия, её свойства; Применение арифметической прогрессии; Числовые последовательности, упорядочивания чисел', 'Aritmētiskā progresija, tās īpašības; Aritmētiskās progresijas pielietojums; Skaitļu virknes, skaitļu sakārtojumi'),
  ('9.8. Как описывают взаимное расположение окружности и многоугольника', '9.8. Kā raksturo riņķa līnijas un daudzstūra savstarpējo novietojumu?', 'skola2030-g9-8-opisyvayut-vzaimnoe-raspolozhenie-okruzhnosti', (select id from public.subjects where slug = 'geometry'), 9, 8, 'Окружность, описанная около треугольника; Правильные многоугольники; Касательная к окружности, вписанная в треугольник окружность; Четырехугольник и окружность', 'Ap trijstūri apvilkta riņķa līnija; Regulāri daudzstūri; Riņķa līnijas pieskare, trijstūrī ievilkta riņķa līnija; Četrstūris un riņķa līnija'),
  ('11.1. Векторы и движение', '11.1. Vektori plaknē un telpā, vektoru darbības', 'skola2030-g11-1-vektory-i-dvizhenie', (select id from public.subjects where slug = 'geometry'), 11, 1, 'Расстояние между двумя точками; Проекция вектора на ось; Векторы в координатной форме на плоскости; Векторы в пространстве; Вектор, его модуль. Расположение векторов; Выражение векторов; Правила сложения векторов', 'Attālums starp diviem punktiem; Vektora projekcija uz ass; Vektori koordinātu formā plaknē; Vektori telpā; Vektors, tā modulis. Vektoru novietojums; Vektoru izteikšana; Vektoru saskaitīšanas likumi'),
  ('11.2. Уравнение линии', '11.2. Taisnes un riņķa līnijas vienādojums', 'skola2030-g11-2-uravnenie-linii', (select id from public.subjects where slug = 'geometry'), 11, 2, 'Линейная функция. Приращение функции и аргумента; Неравенство с 2 переменными; Параллельные и перпендикулярные прямые; Уравнение прямой; Уравнение с 2 переменными. Уравнение окружности', 'Lineāra funkcija. Funkcijas un argumenta pieaugums; Nevienādība ar 2 mainīgajiem; Paralēlas un perpendikulāras taisnes; Taisnes vienādojums; Vienādojums ar 2 mainīgajiem. Riņķa līnijas vienādojums'),
  ('11.3. Комбинаторика и вероятность I', '11.3. Kombinatorika un varbūtību teorija I', 'skola2030-g11-3-kombinatorika-i-veroyatnost-i', (select id from public.subjects where slug = 'statistics'), 11, 3, 'Комбинаторика I; Комбинаторика. Введение; Множества. Действия с множествами; Вероятность суммы. Условная вероятность; Элементы теории вероятностей', 'Kombinatorika I; Kombinatorika. Ievads; Kopas. Darbības ar kopām; Summas varbūtība. Nosacītā varbūtība; Varbūtību teorijas elementi'),
  ('11.4. Статистика I', '11.4. Aprakstošā statistika un izkliedes mēri I', 'skola2030-g11-4-statistika-i', (select id from public.subjects where slug = 'statistics'), 11, 4, 'Меры рассеяния, графическое представление данных; Популяция, выборка и данные. Средние величины', 'Izkliedes mēri, datu grafiska attēlošana; Populācija, izlase un dati. Vidējie lielumi'),
  ('11.5. Дробно-рациональная функция и алгебраические дроби', '11.5. Algebriskās daļas un daļveida racionāla funkcija', 'skola2030-g11-5-drobno-ratsionalnaya-funktsiya-i', (select id from public.subjects where slug = 'algebra'), 11, 5, 'Алгебраические дроби. Область определения; Алгебраические уравнения; Умножение, деление, возведение в степень алгебраических дробей; Сложение и вычитание алгебраических дробей; Сокращение и расширение алгебраических дробей; Дробно-рациональная функция; Тождество. Закон смены знаков; Рациональные алгебраические выражения', 'Algebriskas daļas. Definīcijas kopa; Algebriski vienādojumi; Algebrisko daļu reizināšana, dalīšana, kāpināšana; Algebrisko daļu saskaitīšana un atņemšana; Algebrisku daļu saīsināšana un paplašināšana; Daļveida funkcija; Identitāte. Zīmju maiņas likums; Racionālas algebriskas izteiksmes'),
  ('11.6. Дробно-рациональные уравнения и неравенства', '11.6. Daļveida racionāli vienādojumi un nevienādības', 'skola2030-g11-6-drobno-ratsionalnye-uravneniya-i', (select id from public.subjects where slug = 'algebra'), 11, 6, 'Повторение решения линейных и квадратных неравенств; Дробно-рациональные неравенства. Метод интервалов; Дробно-рациональные уравнения; Дробно-рациональные уравнения в текстовых задачах', 'Atkārtojums par lineāru un kvadrātnevienādību risināšanu; Daļveida nevienādības. Intervālu metode; Daļveida vienādojumi; Daļveida vienādojumi teksta uzdevumos'),
  ('11.7. Функции синуса и косинуса', '11.7. Sinusa un kosinusa funkcijas, sinusu un kosinusu teorēmas', 'skola2030-g11-7-funktsii-sinusa-i-kosinusa', (select id from public.subjects where slug = 'geometry'), 11, 7, 'Синус и косинус угла поворота; Зависимости в прямоугольном треугольнике. Повторение; Теорема синусов и косинусов; Тригонометрические функции, их свойства', 'Pagrieziena leņķa sinuss un kosinuss; Sakarības taisnleņķa trijstūrī. Atkārtojums; Sinusu un kosinusu teorēma; Trigonometriskās funkcijas, to īpašības'),
  ('11.8. Тригонометрические выражения и уравнения', '11.8. Trigonometriskās formulas un pamatvienādojumi', 'skola2030-g11-8-trigonometricheskie-vyrazheniya-i-uravneniya', (select id from public.subjects where slug = 'algebra'), 11, 8, 'Формулы суммы аргументов и двойного аргумента; Метод разложения на множители и метод подстановки; Простейшие тригонометрические уравнения; Тригонометрические выражения и основное тождество', 'Argumentu summas un divkāršā argumenta formulas; Sadalīšana reizinātājos un substitūcijas metode; Trigonometriskie pamatvienādojumi; Trigonometriskās izteiksmes un pamatidentitāte'),
  ('11.9. Степень с рациональным показателем, геометрическая прогрессия', '11.9. Pakāpe ar racionālu kāpinātāju un ģeometriskā progresija', 'skola2030-g11-9-stepen-s-ratsionalnym-pokazatelem', (select id from public.subjects where slug = 'algebra'), 11, 9, 'Корень n-ой степени; Степень с рациональным показателем; Последовательности; Геометрическая прогрессия', 'N-tās pakāpes sakne; Pakāpe ar racionālu kāpinātāju; Virknes; Ģeometriskā progresija'),
  ('11.10. Показательная функция', '11.10. Eksponentfunkcija, eksponentvienādojumi un logaritmi', 'skola2030-g11-10-pokazatelnaya-funktsiya', (select id from public.subjects where slug = 'algebra'), 11, 10, 'Экспоненциальные процессы; Показательная функция; Показательные неравенства; Показательные уравнения; Свойства степеней. Повторение; Простейшие неравенства. Повторение; Простейшие уравнения. Повторение; Логарифм числа', 'Eksponenciāli procesi; Eksponentfunkcija; Eksponentnevienādības; Eksponentvienādojumi; Pakāpju īpašības. Atkārtojums; Pamatnevienādības. Atkārtojums; Pamatvienādojumi. Atkārtojums; Skaitļa logaritms'),
  ('11.11. Прямые и плоскости в пространстве, многогранники', '11.11. Taisnes un plaknes telpā, daudzskaldņi un prizmas', 'skola2030-g11-11-pryamye-i-ploskosti-v', (select id from public.subjects where slug = 'geometry'), 11, 11, 'Диагонали многогранника и сечение плоскостью; Неправильная пирамида; Поверхность и объем призмы; Правильная треугольная пирамида; Правильная четырехугольная и шестиугольная пирамида; Прямые и плоскости в пространстве; Вычисления в прямоугольном треугольнике. Повторение', 'Daudzskaldņa diagonāles un šķēlums ar plakni; Neregulāra piramīda; Prizmas virsma un tilpums; Regulāra trijstūra piramīda; Regulāra četrstūra un sešstūra piramīda; Taisnes un plaknes telpā; Taisnleņķa trijstūra aprēķināšana. Atkārtojums'),
  ('11.12. Тела вращения', '11.12. Rotācijas ķermeņi (cilindrs, konuss, lode)', 'skola2030-g11-12-tela-vrashcheniya', (select id from public.subjects where slug = 'geometry'), 11, 12, 'Геометрические комбинации цилиндра и призмы; Цилиндр; Конус; Шар; Геометрические комбинации шара и призмы', 'Cilindra un prizmas ģeometriskās kombinācijas; Cilindrs; Konuss; Lode; Lodes un prizmas ģeometriskās kombinācijas'),
  ('12.1. Математическая индукция', '12.1. Matemātiskā indukcija, Paskāla trijstūris un Ņūtona binoms', 'skola2030-g12-1-matematicheskaya-induktsiya', (select id from public.subjects where slug = 'statistics'), 12, 1, 'Комбинаторика II. Треугольник Паскаля; Принцип математической индукции; Элементы математической логики; Бином Ньютона', 'Kombinatorika II. Paskāla trijstūris; Matemātiskās indukcijas princips. MIP; Matemātiskās loģikas elementi; Ņūtona binoms'),
  ('12.2. Вероятность и статистика II', '12.2. Varbūtību sadalījumi, Bernulli formula un pilnā varbūtība II', 'skola2030-g12-2-veroyatnost-i-statistika-ii', (select id from public.subjects where slug = 'statistics'), 12, 2, 'Распределения случайной величины. Формула Бернулли; Вероятность объединения событий; Формула полной вероятности; Статистика II', 'Gadījuma lieluma sadalījumi. Bernulli formula; Notikumu apvienojuma varbūtība; Pilnās varbūtības formula; Statistika II'),
  ('12.3. Последовательности и показательная функция', '12.3. Skaitļu virkņu robeža, skaitlis e un bezgalīga ģeometriskā progresija', 'skola2030-g12-3-posledovatelnosti-i-pokazatelnaya-funktsiya', (select id from public.subjects where slug = 'algebra'), 12, 3, 'Бесконечно убывающая геометрическая прогрессия; Число e и экспоненциальные процессы; Последовательности, их монотонность и предел', 'Bezgalīgi dilstoša ģeometriskā progresija; Skaitlis e un eksponenciāli procesi; Virknes, to monotonitāte un robeža'),
  ('12.4. Степенная функция и логарифмическая функция, модуль', '12.4. Pakāpes un logaritmiskā funkcija, moduļa vienādojumi', 'skola2030-g12-4-stepennaya-funktsiya-i-logarifmicheskaya', (select id from public.subjects where slug = 'algebra'), 12, 4, 'Обратная функция; Иррациональные и логарифмические уравнения; Логарифмические уравнения и системы; Логарифмическая функция; Логарифмические неравенства; Функция модуля, уравнения, неравенства; Степенная функция', 'Inversā funkcija; Iracionālie un logaritmiskie vienādojumi; Logaritmiskie vienādojumi un sistēmas; Logaritmiskā funkcija; Logaritmiskās nevienādības; Moduļa funkcija, vienādojumi, nevienādības; Pakāpes funkcija'),
  ('12.5. Дробно-рациональная функция и алгебраические преобразования', '12.5. Polinomu dalīšana, Bezū teorēma un nenoteiktie koeficienti', 'skola2030-g12-5-drobno-ratsionalnaya-funktsiya-i', (select id from public.subjects where slug = 'algebra'), 12, 5, 'Дробно-рациональная функция; Метод неопределенных коэффициентов; Деление многочлена на многочлен. Теорема Безу; Разложение на множители', 'Daļveida funkcija; Nenoteikto koeficientu metode; Polinoma dalīšana ar polinomu. Bezū teorēma; Sadalīšana reizinātājos'),
  ('12.6. Производная и её применение', '12.6. Atvasinājums, diferencēšanas kārtulas un funkciju pētīšana', 'skola2030-g12-6-proizvodnaya-i-eyo-primenenie', (select id from public.subjects where slug = 'algebra'), 12, 6, 'Определение производной и её смысл; Применение производной при исследовании функций; Правила и формулы дифференцирования; Непрерывность функции; Исследование функций в математике и других областях; Предел', 'Atvasinājuma definīcija un interpretācija; Atvasinājuma lietojums funkciju pētīšanā; Atvasināšanas likumi un formulas; Funkcijas nepārtrauktība; Funkciju pētīšana matemātikā un citās jomās; Robeža'),
  ('12.7. Интеграл и его применение', '12.7. Nenoteiktais un noteiktais integrālis, laukumu aprēķināšana', 'skola2030-g12-7-integral-i-ego-primenenie', (select id from public.subjects where slug = 'algebra'), 12, 7, 'Интегрирование дробно-рациональных функций; Вычисление площади и объема с помощью определенного интеграла; Неопределенный интеграл; Определенный интеграл и его применение в физике; Переход к дифференциалу другой функции (замена переменной)', 'Daļveida racionālu funkciju integrēšana; Laukuma un tilpuma aprēķināšana ar noteikto integrāli; Nenoteiktais integrālis; Noteiktais integrālis un integrāļa lietojums fizikā; Pāreja uz citas funkcijas diferenciāli'),
  ('12.8. Тригонометрия II', '12.8. Trigonometriskās nevienādības un inversās trigonometriskās funkcijas', 'skola2030-g12-8-trigonometriya-ii', (select id from public.subjects where slug = 'algebra'), 12, 8, 'Тангенс и котангенс угла; Тригонометрические уравнения и неравенства; Тригонометрические и обратные им функции', 'Leņķa tangenss un kotangenss; Trigonometriskie vienādojumi un nevienādības; Trigonometriskās un to inversās funkcijas'),
  ('12.9. Аналитическая геометрия', '12.9. Analītiskā ģeometrija: taisnes, vektori un skalārais reizinājums', 'skola2030-g12-9-analiticheskaya-geometriya', (select id from public.subjects where slug = 'geometry'), 12, 9, 'Взаимное расположение двух прямых. Точка и прямая; Линии на плоскости; Уравнение прямой; Векторы; Скалярное произведение векторов', 'Divu taišņu savstarpējais novietojums. Punkts un taisne; Līnijas plaknē; Taisnes vienādojums; Vektori; Vektoru skalārais reizinājums'),
  ('12.10. Планиметрия II', '12.10. Padziļinātā planimetrija: sakarības daudzstūros un riņķī', 'skola2030-g12-10-planimetriya-ii', (select id from public.subjects where slug = 'geometry'), 12, 10, 'Углы и отрезки, связанные с окружностью; Зависимости в многоугольниках, правильных многоугольниках; Зависимости в треугольниках; Зависимости в четырехугольниках; Геометрические преобразования', 'Ar riņķa līniju saistītie leņķi un nogriežņi; Sakarības daudzstūros, regulāros daudzstūros; Sakarības trijstūros; Sakarības četrstūros; Ģeometriskie pārveidojumi'),
  ('12.11. Стереометрия II', '12.11. Padziļinātā stereometrija: ķermeņu šķēlumi un kombinācijas', 'skola2030-g12-11-stereometriya-ii', (select id from public.subjects where slug = 'geometry'), 12, 11, 'Многогранники, их сечение плоскостью; Геометрические комбинации конуса и пирамиды; Геометрические комбинации шара, цилиндра и конуса; Геометрические комбинации призмы и цилиндра; Комбинации призмы и шара, пирамиды и шара', 'Daudzskaldņi, to šķēlums ar plakni; Konusa un piramīdas ģeometriskās kombinācijas; Lodes, cilindra un konusa ģeometriskās kombinācijas; Prizmas un cilindra ģeometriskās kombinācijas; Prizmas un lodes, piramīdas un lodes kombinācijas'),
  ('12.12. Комплексные задачи по алгебре', '12.12. Kompleksie uzdevumi algebrā, vienādojumi ar parametriem', 'skola2030-g12-12-kompleksnye-zadachi-po-algebre', (select id from public.subjects where slug = 'algebra'), 12, 12, 'Повторение. Виды простейших уравнений; Метод подстановки. Уравнения и неравенства; Уравнения с параметром; Решение уравнений разложением на множители', 'Atkārtojums. Pamatvienādojumu veidi; Substitūcijas metode. Vienādojumi un nevienādības; Vienādojumi ar parametru; Vienādojumu risināšana, sadalot reizinātājos')
on conflict (slug) do update set
  title = excluded.title,
  title_lv = excluded.title_lv,
  subject_id = excluded.subject_id,
  grade = excluded.grade,
  position = excluded.position,
  description = excluded.description,
  description_lv = excluded.description_lv;

-- 3. Примеры задач стандарта Skola2030 с пошаговыми решениями и мультиязычностью
insert into public.tasks (topic_id, title, title_lv, grade, condition_latex, condition_latex_lv, answer_latex, solution_latex, solution_latex_lv, difficulty, position, is_published)
select
  t.id,
  v.title, v.title_lv,
  v.grade,
  v.condition_latex, v.condition_latex_lv,
  v.answer_latex,
  v.solution_latex, v.solution_latex_lv,
  v.difficulty,
  v.position,
  true
from (
  values
    -- 1 класс: Сложение и вычитание в пределах 10
    (
      'skola2030-g1-2-skolko-vsego-skolko-ostalos',
      'Сложение в пределах 10', 'Saskaitīšana 10 apjomā',
      1,
      'Вычислите значение суммы: $$4 + 3 = ?$$',
      'Aprēķiniet summas vērtību: $$4 + 3 = ?$$',
      '$7$',
      'Прибавим к числу $4$ три единицы: $4 + 1 = 5$, $5 + 1 = 6$, $6 + 1 = 7$. Ответ: $7$.',
      'Pieskaitām skaitlim $4$ trīs vienus: $4 + 1 = 5$, $5 + 1 = 6$, $6 + 1 = 7$. Atbilde: $7$.',
      'Лёгкий', 1
    ),
    -- 7 класс: Линейные уравнения
    (
      'skola2030-g7-8-priemy-opredeleniya-neizvestnogo-lineynoe',
      'Линейное уравнение со скобками', 'Lineārs vienādojums ar iekavām',
      7,
      'Решите уравнение: $$3(2x - 5) + 4 = 5x - 7$$',
      'Atrisiniet vienādojumu: $$3(2x - 5) + 4 = 5x - 7$$',
      '$x = 4$',
      'Раскроем скобки в левой части уравнения:
$$6x - 15 + 4 = 5x - 7$$
$$6x - 11 = 5x - 7$$
Перенесём слагаемые с переменной влево, а числа вправо:
$$6x - 5x = -7 + 11$$
$$x = 4$$',
      'Atveriet iekavas vienādojuma kreisajā pusē:
$$6x - 15 + 4 = 5x - 7$$
$$6x - 11 = 5x - 7$$
Pārnesiet saskaitāmos ar mainīgo pa kreisi, bet skaitļus pa labi:
$$6x - 5x = -7 + 11$$
$$x = 4$$',
      'Средний', 1
    ),
    -- 8 класс: Теорема Пифагора
    (
      'skola2030-g8-8-opredelyayut-neizvestnuyu-storonu-pryamougolnogo',
      'Нахождение гипотенузы', 'Hipotēzes aprēķināšana',
      8,
      'В прямоугольном треугольнике катеты равны $a = 6$ см и $b = 8$ см. Найдите длину гипотенузы $c$.',
      'Taisnleņķa trijstūrī katetes ir $a = 6$ cm un $b = 8$ cm. Aprēķiniet hipotenūzas $c$ garumu.',
      '$10$ см',
      'По теореме Пифагора для прямоугольного треугольника:
$$c^2 = a^2 + b^2$$
Подставим известные значения:
$$c^2 = 6^2 + 8^2 = 36 + 64 = 100$$
Так как длина стороны положительна, $c = \sqrt{100} = 10$ см.',
      'Pēc Pitagora teorēmas taisnleņķa trijstūrī:
$$c^2 = a^2 + b^2$$
Ievietojam dotās vērtības:
$$c^2 = 6^2 + 8^2 = 36 + 64 = 100$$
Tā kā malas garums ir pozitīvs, $c = \sqrt{100} = 10$ cm.',
      'Легкий', 1
    ),
    -- 9 класс: Подобные треугольники
    (
      'skola2030-g9-1-opredelyayut-i-kharakterizuyut-podobnye',
      'Коэффициент подобия треугольников', 'Trijstūru līdzības koeficients',
      9,
      'Треугольники $ABC$ и $A_1B_1C_1$ подобны. Стороны первого треугольника равны $3$, $4$ и $5$, а сходственная меньшая сторона второго треугольника равна $6$. Найдите коэффициент подобия и периметр второго треугольника.',
      'Trijstūri $ABC$ un $A_1B_1C_1$ ir līdzīgi. Pirmā trijstūra malas ir $3$, $4$ un $5$, bet otrā trijstūra atbilstošā mazākā mala ir $6$. Atrodiet līdzības koeficientu un otrā trijstūra perimetru.',
      '$k = 2$, $P = 24$',
      '1) Найдём коэффициент подобия $k$ по отношению наименьших сходственных сторон:
$$k = \frac{6}{3} = 2$$
2) Периметр первого треугольника:
$$P_1 = 3 + 4 + 5 = 12$$
3) Периметр подобного треугольника пропорционален коэффициенту $k$:
$$P_2 = k \cdot P_1 = 2 \cdot 12 = 24$$',
      '1) Atrodam līdzības koeficientu $k$ no mazāko atbilstošo malu attiecības:
$$k = \frac{6}{3} = 2$$
2) Pirmā trijstūra perimetrs:
$$P_1 = 3 + 4 + 5 = 12$$
3) Līdzīgā trijstūra perimetrs ir proporcionāls koeficientam $k$:
$$P_2 = k \cdot P_1 = 2 \cdot 12 = 24$$',
      'Средний', 1
    ),
    -- 11 класс (Matemātika I): Показательные уравнения
    (
      'skola2030-g11-10-pokazatelnaya-funktsiya',
      'Простейшее логарифмическое уравнение', 'Vienkāršs logaritmiskais vienādojums',
      11,
      'Решите уравнение: $$\log_2(x - 3) = 3$$',
      'Atrisiniet vienādojumu: $$\log_2(x - 3) = 3$$',
      '$x = 11$',
      'По определению логарифма $\log_a b = c \iff b = a^c$ при $b > 0$:
$$x - 3 = 2^3 = 8 \implies x = 11$$
Проверка: $11 - 3 = 8 > 0$ — верно.',
      'Pēc logaritma definīcijas:
$$x - 3 = 2^3 = 8 \implies x = 11$$
Pārbaude: $\log_2 8 = 3$ — patiess.',
      'Средний', 1
    ),
    -- 12 класс (Matemātika II): Производная функции
    (
      'skola2030-g12-6-proizvodnaya-i-eyo-primenenie',
      'Производная функции в точке', 'Funkcijas atvasinājums punktā',
      12,
      'Найдите значение производной функции $f(x) = 3x^2 - 4x + 5$ в точке $x_0 = 2$.',
      'Aprēķiniet funkcijas $f(x) = 3x^2 - 4x + 5$ atvasinājuma vērtību punktā $x_0 = 2$.',
      '$f''(2) = 8$',
      'Найдём общую формулу производной:
$$f''(x) = (3x^2)'' - (4x)'' + (5)'' = 6x - 4$$
Подставим $x_0 = 2$:
$$f''(2) = 6 \cdot 2 - 4 = 12 - 4 = 8$$',
      'Atrodiet atvasinājumu:
$$f''(x) = 6x - 4$$
Ievietojiet $x_0 = 2$:
$$f''(2) = 6 \cdot 2 - 4 = 8$$',
      'Средний', 1
    )
) as v(slug, title, title_lv, grade, condition_latex, condition_latex_lv, answer_latex, solution_latex, solution_latex_lv, difficulty, position)
join public.topics t on t.slug = v.slug
where not exists (
  select 1 from public.tasks tk where tk.topic_id = t.id and tk.title = v.title
);
