-- Миграция 019: разрешить восстановление строк с прежними номерами
--
-- Колонки id объявлены как GENERATED ALWAYS AS IDENTITY. Это значит, что
-- вставить строку с явным номером нельзя вовсе:
--   428C9  Column "id" is an identity column defined as GENERATED ALWAYS.
--
-- Для обычной работы это правильно — номер выдаёт база. Но резервная
-- копия становится наполовину бесполезной: изменённую строку она вернуть
-- может, а удалённую — уже нет. Задача получит новый номер, и на неё
-- перестанут указывать кросс-теги, ссылки вида /task/162 и закладки,
-- сохранённые у посетителей в браузере.
--
-- GENERATED BY DEFAULT ведёт себя так же — номер по-прежнему выдаётся
-- сам, — но не запрещает указать его явно, когда это нужно.
--
-- Запускать в Supabase: SQL Editor -> New query -> Run

alter table public.subjects alter column id set generated by default;
alter table public.topics   alter column id set generated by default;
alter table public.tasks    alter column id set generated by default;
alter table public.tags     alter column id set generated by default;

-- После восстановления с явными номерами счётчик может отстать от
-- максимума, и следующая вставка упрётся в занятый номер. Сдвигаем его.
select setval(pg_get_serial_sequence('public.subjects', 'id'), coalesce((select max(id) from public.subjects), 1));
select setval(pg_get_serial_sequence('public.topics',   'id'), coalesce((select max(id) from public.topics),   1));
select setval(pg_get_serial_sequence('public.tasks',    'id'), coalesce((select max(id) from public.tasks),    1));
select setval(pg_get_serial_sequence('public.tags',     'id'), coalesce((select max(id) from public.tags),     1));
