-- Миграция 020: третий уровень каталога — подтемы (n.m.k по Skola2030)
-- Раздел -> тема -> подтема -> задача.
-- Подтема необязательна: задача может лежать прямо в теме, как сейчас.
-- Запускать в Supabase: SQL Editor -> New query -> Run

create table if not exists public.subtopics (
  id bigint generated by default as identity primary key,
  topic_id bigint not null references public.topics(id) on delete cascade,
  title text not null,
  title_lv text,
  slug text not null unique,
  -- Номер вида «7.5.2»: показываем его в интерфейсе и по нему же строим
  -- порядок, поэтому храним готовым, а не собираем каждый раз из позиций.
  code text,
  position int not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists subtopics_topic_id_idx on public.subtopics (topic_id, position);

alter table public.tasks
  add column if not exists subtopic_id bigint references public.subtopics(id) on delete set null;

create index if not exists tasks_subtopic_id_idx on public.tasks (subtopic_id);

alter table public.subtopics enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'subtopics' and policyname = 'Everyone can read subtopics') then
    create policy "Everyone can read subtopics" on public.subtopics for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'subtopics' and policyname = 'Admins manage subtopics') then
    create policy "Admins manage subtopics" on public.subtopics for all to authenticated
      using ((select public.is_admin())) with check ((select public.is_admin()));
  end if;
end $$;
