-- Миграция 025: собранные варианты экзаменов и контрольных работ
-- До сих пор вариант собирался сам: контрольная — из задач темы, экзамен —
-- из задач уровня. Эти две таблицы позволяют собрать вариант руками:
-- выбрать задачи, задать их порядок, время и части. Автоматический вариант
-- никуда не девается — он остаётся, когда собранного варианта нет.
-- Запускать в Supabase: SQL Editor -> New query -> Run

create table if not exists public.exam_papers (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  title_lv text,
  -- exam — пробный экзамен уровня, cw — контрольная работа темы
  kind text not null default 'exam' check (kind in ('exam', 'cw')),
  level text check (level in ('pamat', 'visp', 'opt', 'augst')),
  topic_id bigint references public.topics(id) on delete cascade,
  minutes int not null default 40 check (minutes between 1 and 600),
  -- Части: [{"minutes":105,"title":"1. daļa","title_lv":"1. daļa"}]
  -- Пусто — работа идёт одним отрезком в minutes минут.
  parts jsonb not null default '[]'::jsonb,
  is_published boolean not null default false,
  created_at timestamptz not null default now(),
  -- У экзамена обязателен уровень, у контрольной — тема: иначе вариант
  -- некуда показать.
  constraint exam_papers_target check (
    (kind = 'exam' and level is not null) or (kind = 'cw' and topic_id is not null)
  )
);

create table if not exists public.exam_paper_items (
  id bigint generated by default as identity primary key,
  paper_id bigint not null references public.exam_papers(id) on delete cascade,
  task_id bigint not null references public.tasks(id) on delete cascade,
  position int not null default 0,
  part int not null default 1 check (part between 1 and 9),
  unique (paper_id, task_id)
);

create index if not exists idx_exam_papers_pick on public.exam_papers (kind, is_published);
create index if not exists idx_exam_papers_topic on public.exam_papers (topic_id);
create index if not exists idx_exam_paper_items_paper on public.exam_paper_items (paper_id, part, position);

alter table public.exam_papers enable row level security;
alter table public.exam_paper_items enable row level security;

-- Посетитель видит только опубликованные варианты; черновик варианта —
-- как черновик задачи, он виден лишь администратору.
drop policy if exists "Anyone reads published papers" on public.exam_papers;
create policy "Anyone reads published papers" on public.exam_papers
  for select to anon, authenticated using (is_published);

drop policy if exists "Admins manage papers" on public.exam_papers;
create policy "Admins manage papers" on public.exam_papers
  for all using (public.is_admin()) with check (public.is_admin());

-- Состав варианта виден тогда же, когда и сам вариант.
drop policy if exists "Anyone reads items of published papers" on public.exam_paper_items;
create policy "Anyone reads items of published papers" on public.exam_paper_items
  for select to anon, authenticated using (
    exists (select 1 from public.exam_papers p where p.id = paper_id and p.is_published)
  );

drop policy if exists "Admins manage paper items" on public.exam_paper_items;
create policy "Admins manage paper items" on public.exam_paper_items
  for all using (public.is_admin()) with check (public.is_admin());

grant select on public.exam_papers to anon, authenticated;
grant select on public.exam_paper_items to anon, authenticated;
grant insert, update, delete on public.exam_papers to authenticated;
grant insert, update, delete on public.exam_paper_items to authenticated;
