-- Миграция 029: вернуть сообщение об ошибке под прежним номером
--
-- Миграция 019 перевела id на GENERATED BY DEFAULT у subjects, topics,
-- tasks и tags. Таблица task_reports появилась позже (023) и снова
-- объявила id как GENERATED ALWAYS. С тех пор сообщения учеников попадают
-- в резервную копию, но удалённое сообщение restore.mjs не вернёт:
--   428C9  Column "id" is an identity column defined as GENERATED ALWAYS.
--
-- GENERATED BY DEFAULT ведёт себя так же — номер по-прежнему выдаётся
-- сам, — но не запрещает указать его явно при восстановлении.
--
-- Номера 027 и 028 заняты в ветке feature/learning.
--
-- Запускать в Supabase: SQL Editor -> New query -> Run

alter table public.task_reports alter column id set generated by default;

-- После восстановления с явными номерами счётчик может отстать от
-- максимума, и следующая жалоба упрётся в занятый номер. Сдвигаем его.
select setval(pg_get_serial_sequence('public.task_reports', 'id'), coalesce((select max(id) from public.task_reports), 1));
